local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = "Find files"})
vim.keymap.set('n', '<leader>fw', builtin.live_grep, { desc = "Find word"})
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = "Find buffer"})
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {desc = "Telescope help"})
