return {
    "nvim-treesitter/nvim-treesitter",
    dependencies = { "JoosepAlviste/nvim-ts-context-commentstring" },
    build = ":TSUpdate",
    main = "nvim-treesitter.configs",
    opts = {
        auto_install = true,
        indent = {
            enable = true,
        },
        ensure_installed = {
            "lua",
            "vim",
            "vimdoc",
            "javascript",
            "ssh_config",
            "css",
            "scss",
            "typescript",
            "html",
            "bash",
            "go",
            "gomod",
            "gowork",
            "gosum",
            "json",
            "yaml",
            "ssh_config",
            "regex",
            "toml",
            "json",
            "templ",
            "python",
            "dot",
            "dockerfile",
            "markdown",
            "sql",
            "http",
            "vue",
            "cpp",
            "c",
            "cmake",
        },
        highlight = {
            enable = true,
            additional_vim_regex_highlighting = true,
        },
        matchup = {
            enabled = true,
        },
        context_commentstring = {
            enabled = true,
        },
    },
}
