return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	dependencies = {
		"mason-org/mason.nvim",
	},
	opts = {
		ensure_installed = {
			"stylua",
			"goimports-reviser",
			"gofumpt",
			"golines",
			"sqlfluff",
			"shfmt",
			"golangci-lint",
			"shellcheck",
			"ansible-lint",
			"jsonlint",
			"markdownlint",
			"gomodifytags",
			"impl",
			"iferr",
			"gotests",
			"delve",
			"prettierd",
			"prettier",
			"jq",
			"fixjson",
			"debugpy",
			"ruff",
		},
		auto_install = true,
	},
}
